### ISSUE TITLE
Can not access API from China

### ISSUE THREAD

**Issue by bitnick10** [fxcm/fxcmpy#11]
We know it's blocked.But ,is there have some other server that can make me access the API?

**Comment by FXCMAPI** [comment]
Hello Ginseng,

Thank you for your report. We do have a VPS service that will allow you to connect to virtual machines located in either Europe or the Americas but there is no guarantee that your government would not block that too. This issue is out of the scope of our API Support. It is best that you reach out to your internet service provider to see what your alternatives are to connecting to international APIs.

Best regards,

Mylene Roman
API Support

**Comment by FXCMAPI** [comment]
All our servers are located in USA.  unfortunately, we don;t have servers other than USA.
closing this ticket.
